In [15]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
print iris.feature_names
print iris.target_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [16]:
iris.data[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [17]:
test_idx = [0,60,94]
train_target = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx,axis = 0)

In [18]:
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]
test_data


array([[ 5.1,  3.5,  1.4,  0.2],
       [ 5. ,  2. ,  3.5,  1. ],
       [ 5.6,  2.7,  4.2,  1.3]])

In [19]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data,train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [20]:
clf.predict(test_data)

array([0, 1, 1])

In [21]:
test_target

array([0, 1, 1])